[package]
name = "rust-chat"
description = "A rust telnet-like tiny chat."
version = "0.1.0"
authors = ["julien", "MaeÌˆl Valais <mael.valais@gmail.com>"]

[dependencies]
clap = "2.30"
error-chain = "0.11"
colored = "1.6"
log = "0.4"